//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.27 at 02:15:47 PM PST 
//
package statutesrs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import statutes.StatutesBaseClass;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statutesRootWithReferences", propOrder = {
    "statutesPath", "finalReferences"
})
public class ReferencesWithReferences {

    @XmlElement
    protected List<StatutesBaseClass> statutesPath;
    
	@XmlElement(nillable = true)
    protected List<StatutesBaseClass> finalReferences;

    public List<StatutesBaseClass> getStatutesPath() {
        if (statutesPath == null) {
        	statutesPath = new ArrayList<>();
        }
        return this.statutesPath;
    }

    public List<StatutesBaseClass> getFinalReferences() {
        if (finalReferences == null) {
        	finalReferences = new ArrayList<>();
        }
        return this.finalReferences;
    }
}
